config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  resources :binge_series do
    namespace :season, path: ':season', module: nil do
      resources :binge_episodes, controller: 'binge_episodes'
    end
  end

  devise_for :users

  root 'binge_series#index'
end

app/models/binge_episode.rb
class BingeEpisode < ActiveRecord::Base
  validates_presence_of :name, :description, :season
  belongs_to :binge_serie
end

app/models/binge_serie.rb
class BingeSerie < ActiveRecord::Base
  validates_presence_of :title, :description, :image
  has_many :binge_episodes
  mount_uploader :image, ImageUploader

  def seasons
    binge_episodes.pluck(:season).uniq.sort
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates_presence_of :username
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/binge_episodes_controller.rb
class BingeEpisodesController < ApplicationController
  before_action :set_binge_serie

  def index
    @episodes = @binge_series.binge_episodes.
      where(season: params[:season])

      respond_to do |f|
        f.html
        f.json {render json: {binge_serie: @binge_series, binge_episodes: @episodes } }
      end
  end

  def show
    @episode = @binge_series.binge_episodes.
      where(season: params[:season]).
      find(params[:id])

    respond_to do |f|
      f.html
      f.json{render json: {binge_series: @binge_series, binge_episodes: @episode } }
    end
  end

  protected

  def set_binge_serie
    @binge_series = BingeSerie.find(params[:binge_series_id])
  end

end

app/controllers/binge_series_controller.rb
class BingeSeriesController < ApplicationController
  before_action :set_binge_serie, only: [:show]

  def index
    @series = BingeSerie.all

    respond_to do |f|
      f.html
      f.json {render json: { binge_series: @series } }
    end
  end

  def show
    @serie = BingeSerie.find(params[:id])

    respond_to do |f|
      f.html
      f.json {render json: { binge_series: @serie.attributes.merge({seasons: @serie.seasons})} }
    end
  end

  protected

    def set_binge_serie
      @binge_series = BingeSerie.find(params[:id])
    end
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/binge_episodes_helper.rb
module BingeEpisodesHelper
end

app/helpers/binge_series_helper.rb
module BingeSeriesHelper
end

app/views/binge_episodes/index.html.erb
<h1><%= @binge_series.title %></h1>
<%= image_tag(@binge_series.image, style: "width: 450px; height: 250px;") %>

<h3>Here you can see all the episodes of season <%= params[:season]%></h3>

<% @episodes.each do | e | %>
  <div class="episode">
    <%= link_to binge_series_season_binge_episode_path(@binge_series.id, e.id, season: params[:season]) do %>
      <p>Ep. <%= e.episode %> -- <%= e.name %></p>
    <% end %>
  </div>
<% end %>

app/views/binge_episodes/show.html.erb
<h1><%= @binge_series.title %></h1>

<p><%= image_tag(@binge_series.image, style: "width: 450px; height: 250px;") %></p>


<h2>Season. <%= params[:season] %> <br />
  Ep. <%= @episode.episode %> --
<%= @episode.name %></h2><br />

<%= simple_format @episode.description %>

app/views/binge_series/index.html.erb
<h1>BingeSeries</h1>

<p> Welcome to BingeTracker!
    Here you can follow all the series that you watch
</p>

<p>
   You can click one of the series below to see all its episodes
</p>

<% @series.each do |serie| %>
  <div class="serie-overview">
    <%= link_to serie.title, binge_series_path(serie.id) %>
    <%= @seasons %>
  </div>
<% end %>

app/views/binge_series/show.html.erb
<h1> Here you can find all the episodes of <%= @serie.title %></h1>

<p><%= @serie.description %></p>
<% @serie.seasons.each do | s | %>
  <%= link_to binge_series_season_binge_episodes_path(@serie.id, season: s) do %>
    <h3>Season <%= s %></h3>
  <% end %>
<% end %>

  <p><%= image_tag(@serie.image, style: "width: 450px; height: 250px;") %></p>

app/views/hello_world/index.html.erb
<h1 class="alert alert-info this-works">Client Rendering</h1>
<%= react_component("HelloWorldApp",
                     props: @hello_world_props,
                     prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BingeTrackerApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>